name: rydex_driver_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.25.2
  firebase_auth: ^4.17.2
  firebase_storage: ^11.6.3
  cloud_firestore: ^4.13.6
  path_provider: ^2.0.15
  fl_chart: ^0.40.0
  dropdown_button2: ^2.3.9
  flutter_form_builder: ^7.7.0
  animated_snack_bar: ^0.3.1
  form_builder_validators: ^9.0.0
  permission_handler: ^10.2.0
  email_validator: ^2.1.17
  flutter_onboarding_slider: ^1.0.9
  font_awesome_flutter: ^10.4.0
  form_field_validator: ^1.1.0
  intro_slider: ^4.2.0
  google_fonts: ^4.0.4
  simple_fontellico_progress_dialog: ^0.3.0
  lottie: ^2.6.0
  bezier_chart_plus: ^0.0.1
  flutter_settings_screens: ^0.3.3-null-safety+2
  pedantic: ^1.11.1
  settings_ui: ^2.0.2
  flashy_tab_bar2: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  intl: ^0.18.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          style: italic

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf
          weight: 700



  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - lib/src/data/cashFlowData.json

    -
      #    - assets/images/onboarding_images/
      #    - assets/images/moving_taxi.png


















